const data = {
  products: [
    {
      name: 'canon camera',
      slug: 'canon-camera',
      category: 'Camera',
      image: '/images/p1.jpg',
      price: 120,
      countInstock: 10,
      brand: 'canon',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality',
    },
    {
      name: 'nikon camera',
      slug: 'nikon-camera',
      category: 'Camera',
      image: '/images/p2.jpg',
      price: 250,
      countInstock: 10,
      brand: 'nikon',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality',
    },
    {
      name: 'sony',
      slug: 'sony-camera',
      category: 'Camera',
      image: '/images/p3.jpg',
      price: 25,
      countInStock: 15,
      brand: 'sony',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality',
    },
    {
      name: 'Ring light',
      slug: 'ring-light',
      category: 'holder',
      image: '/images/p4.jpg',
      price: 65,
      countInstock: 5,
      brand: 'sony',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality',
    },
  ],
};
export default data;
